import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:path/path.dart' as p;

/// Result of a successful PDF pick operation.
///
/// Carries everything [PdfReadingTrackerViewer] (and the example app) needs:
/// - [filePath]  — absolute path on device; pass directly to [AlhPdfView].
/// - [pdfId]     — stable, filesystem-safe identifier for SQLite keying.
/// - [title]     — human-readable filename for display in the UI.
class PickedPdf {
  const PickedPdf({
    required this.filePath,
    required this.pdfId,
    required this.title,
  });

  /// Absolute path to the picked file on the device filesystem.
  final String filePath;

  /// Stable SQLite key derived from [filePath].
  ///
  /// Generated by sanitising the absolute path so it can be used as a
  /// filename-safe string. Using the full path (rather than a random UUID)
  /// means the same file always maps to the same progress/bookmark records —
  /// i.e. re-picking the same file resumes where the user left off.
  final String pdfId;

  /// Human-readable display name (the file's basename).
  final String title;
}

/// Wraps [FilePicker] and provides a single, typed entry-point for PDF picking.
///
/// ### Usage
/// ```dart
/// final picked = await PdfPickerService.pickPdf();
/// if (picked != null) {
///   // open PdfReadingTrackerViewer with picked.filePath
/// }
/// ```
abstract final class PdfPickerService {
  PdfPickerService._();

  /// Opens the OS file picker filtered to PDF files.
  ///
  /// Returns a [PickedPdf] when the user selects a file, or `null` if the
  /// picker is dismissed without a selection.
  ///
  /// Throws a [PdfPickerException] if the picked path cannot be resolved or
  /// the selected file does not exist on disk.
  static Future<PickedPdf?> pickPdf() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf'],
      allowMultiple: false,
      withData: false, // stream from path, don't load into memory
    );

    if (result == null || result.files.isEmpty) return null;

    final platformFile = result.files.single;
    final path = platformFile.path;

    if (path == null) {
      throw const PdfPickerException(
        'File path could not be resolved. '
            'On some platforms withData must be true — '
            'check file_picker configuration.',
      );
    }

    if (!File(path).existsSync()) {
      throw PdfPickerException('Picked file does not exist on disk: $path');
    }

    return PickedPdf(
      filePath: path,
      pdfId: _pathToPdfId(path),
      title: p.basenameWithoutExtension(path),
    );
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// Converts an absolute file path into a stable, filesystem-safe [pdfId].
  ///
  /// Example:
  ///   `/data/user/0/com.example/files/my report.pdf`
  ///   → `user_pdf__data_user_0_com_example_files_my_report_pdf`
  ///
  /// The `user_pdf_` prefix lets the UI distinguish user-picked PDFs from
  /// asset-backed PDFs when iterating [ReadingProgress] records.
  static String _pathToPdfId(String absolutePath) {
    final sanitised = absolutePath
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_');
    return 'user_pdf_$sanitised';
  }
}

// ---------------------------------------------------------------------------
// Exception
// ---------------------------------------------------------------------------

class PdfPickerException implements Exception {
  const PdfPickerException(this.message);
  final String message;
  @override
  String toString() => 'PdfPickerException: $message';
}