import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

/// Result of a successful PDF pick operation.
///
/// Carries everything [PdfReadingTrackerViewer] (and the example app) needs:
/// - [filePath]  — **persistent** absolute path inside ApplicationDocumentsDirectory.
/// - [pdfId]     — stable, filesystem-safe identifier for SQLite keying.
/// - [title]     — human-readable filename for display in the UI.
class PickedPdf {
  const PickedPdf({
    required this.filePath,
    required this.pdfId,
    required this.title,
  });

  /// Absolute path to the copied file inside ApplicationDocumentsDirectory.
  ///
  /// This path is permanent — it survives app restarts, cache clears, and OS
  /// temp-file eviction.  Never store the raw FilePicker cache path.
  final String filePath;

  /// Stable SQLite key derived from the *destination* [filePath].
  ///
  /// Generated by sanitising the absolute path so it can be used as a
  /// filename-safe string. Using the destination path (rather than a random
  /// UUID) means re-picking the same file always maps to the same
  /// progress/bookmark records — i.e. the user resumes where they left off.
  final String pdfId;

  /// Human-readable display name (the file's basename without extension).
  final String title;
}

/// Wraps [FilePicker] and provides a single, typed entry-point for PDF picking.
///
/// **v2.1.1 fix — persistent storage**
/// The raw path returned by `FilePicker` is a *cache* path on both Android
/// (FileProvider temp URI) and iOS (Inbox directory).  Those files are deleted
/// by the OS between sessions, which caused the "File not found" bug.
///
/// `pickPdf` now copies the selected file into
/// `ApplicationDocumentsDirectory/user_pdfs/` before returning.  The returned
/// [PickedPdf.filePath] always points to the persistent copy.
///
/// ### Migration of already-saved records
/// Existing records that stored a cache path will surface as "File not found"
/// once the cache is cleared — nothing can be done for those.  Records picked
/// after upgrading to this version will always resolve correctly.
///
/// ### Usage
/// ```dart
/// final picked = await PdfPickerService.pickPdf();
/// if (picked != null) {
///   // open PdfReadingTrackerViewer with picked.filePath / picked.pdfId
/// }
/// ```
abstract final class PdfPickerService {
  PdfPickerService._();

  // Subdirectory inside ApplicationDocumentsDirectory where PDFs are stored.
  static const _kPdfSubdir = 'user_pdfs';

  /// Opens the OS file picker filtered to PDF files.
  ///
  /// Returns a [PickedPdf] when the user selects a file, or `null` if the
  /// picker is dismissed without a selection.
  ///
  /// The selected file is **copied** into a persistent directory before this
  /// method returns; callers never see a temp/cache path.
  ///
  /// Throws a [PdfPickerException] if the picked path cannot be resolved,
  /// the source file does not exist, or the copy operation fails.
  static Future<PickedPdf?> pickPdf() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf'],
      allowMultiple: false,
      withData: false, // stream from path — don't load into memory
    );

    if (result == null || result.files.isEmpty) return null;

    final platformFile = result.files.single;
    final sourcePath = platformFile.path;

    if (sourcePath == null) {
      throw const PdfPickerException(
        'File path could not be resolved. '
            'On some platforms withData must be true — '
            'check file_picker configuration.',
      );
    }

    final sourceFile = File(sourcePath);
    if (!sourceFile.existsSync()) {
      throw PdfPickerException(
        'Picked file does not exist on disk: $sourcePath',
      );
    }

    // ------------------------------------------------------------------
    // Copy to persistent storage
    // ------------------------------------------------------------------
    final persistentPath = await _copyToPersistentStorage(
      sourceFile: sourceFile,
      originalName: platformFile.name,
    );

    return PickedPdf(
      filePath: persistentPath,
      pdfId: _pathToPdfId(persistentPath),
      title: p.basenameWithoutExtension(persistentPath),
    );
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /// Copies [sourceFile] into `<ApplicationDocumentsDirectory>/user_pdfs/`
  /// and returns the destination absolute path.
  ///
  /// If the destination already exists (same filename), the file is
  /// overwritten so the user always gets the latest version they picked.
  static Future<String> _copyToPersistentStorage({
    required File sourceFile,
    required String originalName,
  }) async {
    try {
      final docsDir = await getApplicationDocumentsDirectory();
      final pdfDir = Directory(p.join(docsDir.path, _kPdfSubdir));
      if (!pdfDir.existsSync()) {
        await pdfDir.create(recursive: true);
      }

      // Keep the original filename so the title stays human-readable.
      // If a file with the same name exists and has different content, we
      // overwrite it — the user explicitly re-picked it.
      final destPath = p.join(pdfDir.path, _sanitiseFilename(originalName));
      await sourceFile.copy(destPath);

      // ── Cache cleanup ─────────────────────────────────────────────────
      // Delete the specific temp file that FilePicker wrote (Android
      // FileProvider cache or iOS Inbox). This is the exact file we just
      // successfully copied, so deletion is safe.
      // Wrapped in its own try/catch — a cleanup failure must never
      // propagate to the caller or undo the successful copy.
      try {
        if (await sourceFile.exists()) {
          await sourceFile.delete();
        }
      } catch (_) {
        // Non-fatal: OS may have already evicted the file, or it may live
        // on a path we do not have delete permission for (e.g. external
        // storage on some Android OEMs). The persistent copy is safe.
      }

      // Sweep any other orphaned FilePicker temp files from previous
      // sessions. clearTemporaryFiles() is a no-op on platforms where
      // FilePicker has nothing to clear, so it is always safe to call.
      try {
        await FilePicker.platform.clearTemporaryFiles();
      } catch (_) {
        // Non-fatal: same rationale as above.
      }
      // ─────────────────────────────────────────────────────────────────

      return destPath;
    } catch (e) {
      throw PdfPickerException('Failed to copy PDF to persistent storage: $e');
    }
  }

  /// Strips characters that are unsafe in filenames, collapsing runs of
  /// underscores and ensuring the `.pdf` extension is preserved.
  static String _sanitiseFilename(String name) {
    // Keep alphanumeric, dots, hyphens, underscores, spaces.
    final safe = name
        .replaceAll(RegExp(r'[^\w.\- ]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .trim();
    // Guarantee .pdf extension.
    if (!safe.toLowerCase().endsWith('.pdf')) return '$safe.pdf';
    return safe;
  }

  /// Converts an absolute *persistent* file path into a stable,
  /// filesystem-safe [pdfId] for use as a SQLite key.
  ///
  /// Example:
  ///   `/data/user/0/com.example/files/user_pdfs/my_report.pdf`
  ///   → `user_pdf__data_user_0_com_example_files_user_pdfs_my_report_pdf`
  ///
  /// The `user_pdf_` prefix lets callers distinguish user-picked PDFs from
  /// asset-backed PDFs when iterating [ReadingProgress] records.
  static String _pathToPdfId(String absolutePath) {
    final sanitised = absolutePath
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_');
    return 'user_pdf_$sanitised';
  }
}

// ---------------------------------------------------------------------------
// Exception
// ---------------------------------------------------------------------------

class PdfPickerException implements Exception {
  const PdfPickerException(this.message);
  final String message;

  @override
  String toString() => 'PdfPickerException: $message';
}